exclude:
  - "lib/**"
  - "node_modules/**"
  - "dist/**"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    width: 1
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
  NameFormat:
    enabled: false
  UrlFormat:
    enabled: false

# Temporary execptions
  FinalNewline:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  PropertySortOrder:
    enabled: false
  SpaceAfterComma:
    enabled: false
  UrlQuotes:
    enabled: false
  SingleLinePerSelector:
    enabled: false
